kind: Deployment
apiVersion: apps/v1
metadata:
   name: pro_devops
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: pro_devops
   template:
      metadata:
        labels:
          app: pro_devops
      spec:
       containers:
        - name: pro_devops
          image: suribau/project:v1.latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
