kind: Service                             
apiVersion: v1
metadata:
  name: pro_devops
  labels:
    app: pro_devops
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: pro_devops                    
  type: LoadBalancer
